# Generated by Django 5.2 on 2026-09-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("engine", "0107_remove_annotationguide_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameMaskRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("frame", models.PositiveIntegerField()),
                ("points", models.JSONField()),
                ("z_order", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mask_regions",
                        related_query_name="mask_region",
                        to="engine.job",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="framemaskregion",
            index=models.Index(fields=["job", "frame"], name="engine_fram_job_id_2783da_idx"),
        ),
    ]
