# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0108_frame_mask_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="framemaskregion",
            name="color",
            field=models.CharField(default="#000000", max_length=32),
        ),
    ]
