# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0109_frame_mask_region_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="framemaskregion",
            name="track_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="framemaskregion",
            name="is_keyframe",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="framemaskregion",
            name="outside",
            field=models.BooleanField(default=False),
        ),
    ]
